In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow import keras
import matplotlib.pyplot as plt
%matplotlib inline

C:\Users\User\AppData\Local\Temp\ipykernel_9828\800486908.py:2: DeprecationWarning: 
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466
        
  import pandas as pd


In [2]:
df=pd.read_csv("insurance_data.csv")
df.head()

,age,affordibility,bought_insurance
0,22,1,0
1,25,0,0
2,47,1,1
3,52,0,0
4,46,1,1


In [3]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(df[['age','affordibility']],df.bought_insurance,test_size=0.2,random_state=25)

In [4]:
len(X_train)

22

In [5]:
X_train_scaled=X_train.copy()
X_train_scaled['age']=X_train_scaled['age']/100

X_test_scaled=X_test.copy()
X_test_scaled['age']=X_test_scaled['age']/100

In [6]:
X_train_scaled.head()

,age,affordibility
0,0.22,1
13,0.29,0
6,0.55,0
17,0.58,1
24,0.50,1


In [7]:
model=keras.Sequential([
    keras.layers.Dense(1,input_shape=(2,),activation='sigmoid',kernel_initializer='ones',bias_initializer='zeros')
])

C:\Users\User\AppData\Roaming\Python\Python311\site-packages\keras\src\layers\core\dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [8]:
model.compile(optimizer='adam',
              loss='binary_crossentropy',
              metrics=['accuracy'])

In [9]:
model.fit(X_train_scaled,y_train,epochs=5000)

Epoch 1/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 880ms/step - accuracy: 0.5000 - loss: 0.7113
Epoch 2/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.5000 - loss: 0.7110
Epoch 3/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.5000 - loss: 0.7106
Epoch 4/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.5000 - loss: 0.7102
Epoch 5/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.5000 - loss: 0.7098
Epoch 6/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.5000 - loss: 0.7094
Epoch 7/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.5000 - loss: 0.7091
Epoch 8/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.5000 - loss: 0.7087
Epoch 9/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.5000 - loss: 0.7083
Epoch 10/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.5000 - loss: 0.7079
Epoch 11/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.5000 - loss: 0.7076
Epoch 12/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy

In [10]:
model.evaluate(X_test_scaled,y_test)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 170ms/step - accuracy: 1.0000 - loss: 0.3550


[0.35497763752937317, 1.0]

In [11]:
model.predict(X_test_scaled)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step


array([[0.70548475],
       [0.3556957 ],
       [0.16827832],
       [0.4780119 ],
       [0.72606957],
       [0.82949823]], dtype=float32)

In [12]:
y_test

2     1
10    0
21    0
11    0
14    1
9     1
Name: bought_insurance, dtype: int64

In [13]:
coef,intercept=model.get_weights()
coef,intercept

(array([[5.0608625],
        [1.408652 ]], dtype=float32),
 array([-2.9137027], dtype=float32))

In [14]:
def sigmoid(x):
    import math
    return (1/(1+math.exp(-x)))

In [15]:
sigmoid(15)

0.999999694097773

In [16]:
def prediction_function(age,affordibility):
    y=coef[0]*age+coef[1]*affordibility+intercept
    return sigmoid(y)

In [17]:
prediction_function(0.47,1)

C:\Users\User\AppData\Local\Temp\ipykernel_9828\1219326287.py:3: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  return (1/(1+math.exp(-x)))


0.7054847702382996

In [18]:
def Binary_crossentropy(y_true,y_predicted):
    epsilon=1e-15
    y_predicted_new=np.array([max(i,epsilon) for i in y_predicted])
    y_predicted_new=np.array([min(i,1-epsilon) for i in y_predicted_new])
    log_loss=-np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))

    return log_loss

In [19]:
def sigmoid_numpy(x):
    return (1/np.exp(-x))

In [20]:
sigmoid_numpy(np.array([12,1,0]))

array([1.62754791e+05, 2.71828183e+00, 1.00000000e+00])

Gradient descent by plane python

In [21]:
def gradient_descent(age,affordibility,y_true,epochs,min_thresold):
    #output will be -> w1,w2,b
    w1=w2=1
    bias=0
    learning_rate=0.01
    n=len(age)

    for i in range(epochs):
        weighted_sum=w1*age+w2*affordibility+bias
        y_predicted=sigmoid_numpy(weighted_sum)

        loss=Binary_crossentropy(y_true,y_predicted)

        w1d=(1/n)*np.dot((y_predicted-y_true),np.transpose(age))
        w2d=(1/n)*np.dot((y_predicted-y_true),np.transpose(affordibility))

        bias_d=np.mean(y_predicted-y_true)

        w1=w1-learning_rate*w1d
        w2=w2-learning_rate*w2d
        bias=bias-learning_rate*bias_d

        print(f"Epoch:{i}, W1:{w1}, w2:{w2}, b:{bias}, loss:{loss}")

        if(loss<=min_thresold):
            break

    return w1,w2,bias

In [22]:
gradient_descent(X_train_scaled['age'],X_train_scaled['affordibility'],y_train,5000,0.5142)

Epoch:0, W1:0.9884940686445631, w2:0.9773313061086774, b:-0.027060099272117246, loss:17.26978799617044
Epoch:1, W1:0.9776972852920576, w2:0.9560912400009733, b:-0.05252704106070282, loss:17.26978799617044
Epoch:2, W1:0.9675330650429769, w2:0.9361232899921385, b:-0.07657176760090818, loss:17.26978799617044
Epoch:3, W1:0.9579367024304617, w2:0.9172954039013133, b:-0.09933881002467407, loss:17.26978799617044
Epoch:4, W1:0.948853018965161, w2:0.8994951232805822, b:-0.1209515042885419, loss:17.26978799617044
Epoch:5, W1:0.9402345682365916, w2:0.8826258744284255, b:-0.14151597336825697, loss:17.26978799617044
Epoch:6, W1:0.9320402466163019, w2:0.8666041002232072, b:-0.16112421142703168, loss:17.26978799617044
Epoch:7, W1:0.9242342039574518, w2:0.8513570133489935, b:-0.17985650339775053, loss:17.26978799617044
Epoch:8, W1:0.9167849795161126, w2:0.8368208156581939, b:-0.1977833453571908, loss:15.948102268104417
Epoch:9, W1:0.9096648092531227, w2:0.8229392719591737, b:-0.21496698483352733, loss

(1.2213412826417385, 0.6332985435635082, -1.6265773675101587)

In [23]:
coef,intercept

(array([[5.0608625],
        [1.408652 ]], dtype=float32),
 array([-2.9137027], dtype=float32))