In [1]:
import numpy as np

In [3]:
mat_A=np.array([[1,2,3],[4,5,6],[7,8,9]])
mat_B=np.array([[1,3,5],[7,9,11],[13,15,17]])

In [5]:
mat_A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
mat_B

array([[ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17]])

In [7]:
mat_A+mat_B

array([[ 2,  5,  8],
       [11, 14, 17],
       [20, 23, 26]])

In [8]:
mat_A-mat_B

array([[ 0, -1, -2],
       [-3, -4, -5],
       [-6, -7, -8]])

In [10]:
np.dot(mat_A,mat_B)

array([[ 54,  66,  78],
       [117, 147, 177],
       [180, 228, 276]])